package id.ars.hey;
import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.projection.MediaProjectionManager;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.concurrent.Executors;

public final class MainActivity extends Activity implements StateStore.Listener {
  private HeyApp app;private final Handler main=new Handler(Looper.getMainLooper());private final java.util.concurrent.ExecutorService network=Executors.newSingleThreadExecutor();
  private LinearLayout root,content,nav;private TextView connection,detail,taskTitle,taskDetail,taskTime,taskCounts;private ImageView browserImage;private Bitmap shown;private String page="Home";private float downX,downY;
  private final int ink=Color.rgb(35,42,37),muted=Color.rgb(108,117,108),green=Color.rgb(51,82,61),background=Color.rgb(243,242,239);
  @Override public void onCreate(Bundle state){super.onCreate(state);app=(HeyApp)getApplication();app.state.listen(this);getWindow().setStatusBarColor(background);getWindow().setNavigationBarColor(background);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);build();pairIntent(getIntent());}
  @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);pairIntent(intent);}
  private int dp(float v){return (int)(getResources().getDisplayMetrics().density*v+.5f);}
  private GradientDrawable surface(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));d.setStroke(dp(1),Color.argb(18,40,58,45));return d;}
  private TextView text(String value,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setTypeface(Typeface.create(bold?"sans-serif-medium":"sans-serif",Typeface.NORMAL));t.setLineSpacing(dp(3),1);return t;}
  private void space(LinearLayout target,int height){View v=new View(this);target.addView(v,new LinearLayout.LayoutParams(1,dp(height)));}
  private Button button(String label,Runnable action,boolean primary){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(15);b.setTextColor(primary?Color.WHITE:ink);b.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));b.setBackground(surface(primary?green:Color.rgb(236,239,233),15));b.setPadding(dp(12),dp(8),dp(12),dp(8));b.setOnClickListener(v->action.run());LinearLayout.LayoutParams params=new LinearLayout.LayoutParams(-1,dp(54));params.topMargin=dp(12);b.setLayoutParams(params);return b;}
  private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(22),dp(22),dp(22),dp(22));c.setBackground(surface(Color.rgb(255,254,251),24));c.setElevation(dp(3));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(1),dp(4),dp(1),dp(18));c.setLayoutParams(p);return c;}
  private void build(){
    root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(background);root.setPadding(dp(20),dp(18),dp(20),dp(12));setContentView(root);
    root.setOnApplyWindowInsetsListener((v,insets)->{Insets i=insets.getInsets(WindowInsets.Type.systemBars());v.setPadding(dp(20)+i.left,dp(12)+i.top,dp(20)+i.right,dp(8)+i.bottom);return insets;});
    LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);TextView wordmark=text("Hey",31,ink,true);header.addView(wordmark);TextView by=text("  by Ars",13,muted,false);header.addView(by);root.addView(header);space(root,16);
    ScrollView scroll=new ScrollView(this);scroll.setFillViewport(false);scroll.setClipToPadding(false);scroll.setVerticalScrollBarEnabled(false);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
    nav=new LinearLayout(this);nav.setPadding(dp(4),dp(4),dp(4),dp(4));nav.setBackground(surface(Color.rgb(230,233,226),20));root.addView(nav,new LinearLayout.LayoutParams(-1,dp(56)));render();
  }
  private void render(){content.removeAllViews();connection=detail=taskTitle=taskDetail=taskTime=taskCounts=null;browserImage=null;nav.removeAllViews();for(String name:new String[]{"Home","Browser","Tasks","Settings"}){TextView tab=text(name,12,name.equals(page)?green:muted,name.equals(page));tab.setGravity(Gravity.CENTER);if(name.equals(page))tab.setBackground(surface(Color.WHITE,16));tab.setOnClickListener(v->{page=name;render();});nav.addView(tab,new LinearLayout.LayoutParams(0,-1,1));}
    switch(page){case "Browser":browser();break;case "Tasks":tasks();break;case "Settings":settings();break;default:home();}
    if(Settings.Global.getFloat(getContentResolver(),Settings.Global.ANIMATOR_DURATION_SCALE,1)>0){content.setAlpha(.65f);content.setTranslationY(dp(5));content.animate().alpha(1).translationY(0).setDuration(220).start();}update();
  }
  private void home(){space(content,22);content.addView(text("A little hello.",35,ink,true));content.addView(text("Ruang untuk browsermu.",18,muted,false));space(content,30);LinearLayout c=card();connection=text("Memeriksa…",18,green,true);c.addView(connection);detail=text("",14,muted,false);space(c,8);c.addView(detail);
    c.addView(button(app.secure.get("deviceToken","").isEmpty()?"Hubungkan dari ChatGPT":"Siapkan browser",()->{if(app.secure.get("deviceToken","").isEmpty())new AlertDialog.Builder(this).setTitle("Satu koneksi, sekali saja").setMessage("Di ChatGPT, panggil Hey dan minta hubungkan ponsel. Buka tautan pairing yang diberikan pada ponsel ini.").setPositiveButton("Mengerti",null).show();else startBrowser();},true));content.addView(c);
    LinearLayout control=card();control.addView(text("Tetap di tanganmu.",18,ink,true));space(control,8);control.addView(text("Lihat browser yang sedang bekerja, ambil alih kapan pun, atau jeda seluruh aktivitas.",14,muted,false));control.addView(button("Lihat browser",()->{page="Browser";render();},false));content.addView(control);
  }
  private void browser(){content.addView(text("Your browser.",29,ink,true));content.addView(text("Surface yang sama untuk kamu dan Hey.",14,muted,false));space(content,14);LinearLayout c=card();browserImage=new ImageView(this);browserImage.setScaleType(ImageView.ScaleType.FIT_CENTER);browserImage.setBackground(surface(Color.rgb(237,240,233),16));browserImage.setContentDescription("Tampilan langsung browser Hey");c.addView(browserImage,new LinearLayout.LayoutParams(-1,dp(350)));
    browserImage.setOnTouchListener((v,e)->{HeyService service=HeyService.current;if(service==null||service.browser==null||!app.state.snapshot().optString("control").equals("HUMAN"))return false;float w=v.getWidth(),h=v.getHeight(),scale=Math.min(w/720f,h/1280f),left=(w-720*scale)/2,top=(h-1280*scale)/2;float x=(e.getX()-left)/scale,y=(e.getY()-top)/scale;if(e.getAction()==MotionEvent.ACTION_DOWN){downX=x;downY=y;return true;}if(e.getAction()==MotionEvent.ACTION_UP){service.browser.manualTouch(downX,downY,x,y);v.performClick();return true;}return true;});
    c.addView(button(app.state.snapshot().optString("control").equals("HUMAN")?"Kembalikan ke Hey":"Ambil alih",()->{HeyService s=HeyService.current;if(s!=null){s.control(!app.state.snapshot().optString("control").equals("HUMAN"));render();}},true));
    c.addView(button("Pilih file untuk halaman ini",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,40);},false));content.addView(c);
    LinearLayout navigate=card();EditText url=new EditText(this);url.setSingleLine(true);url.setHint("https://…");url.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);navigate.addView(url);navigate.addView(button("Buka halaman",()->{HeyService s=HeyService.current;if(s==null){startBrowser();return;}if(!app.state.snapshot().optString("control").equals("HUMAN")){Toast.makeText(this,"Ambil alih browser terlebih dahulu",Toast.LENGTH_SHORT).show();return;}try{String address=url.getText().toString();BrowserRuntime.publicUrl(address);s.control(false);s.browser.execute("navigate",new JSONObject().put("url",address),(o,error)->{s.control(true);if(error!=null)Toast.makeText(this,"Halaman belum dapat dibuka",Toast.LENGTH_SHORT).show();});}catch(Exception e){Toast.makeText(this,"Gunakan alamat HTTPS publik",Toast.LENGTH_SHORT).show();}},false));content.addView(navigate);
  }
  private void tasks(){content.addView(text("A clear trail.",29,ink,true));space(content,18);LinearLayout c=card();taskTitle=text("",19,green,true);taskDetail=text("",14,muted,false);taskTime=text("",30,ink,true);taskCounts=text("",13,muted,false);c.addView(taskTitle);c.addView(taskDetail);space(c,12);c.addView(taskTime);c.addView(taskCounts);content.addView(c);updateTasks();}
  private void updateTasks(){if(taskTitle==null)return;JSONObject state=app.state.snapshot();if(!state.optString("taskId").isEmpty()){taskTitle.setText("Sedang bekerja");taskDetail.setText("Progress diamati langsung dari browser.");JSONObject p=state.optJSONObject("progress");taskTime.setText(p!=null&&p.has("currentTime")?String.format(java.util.Locale.US,"%.1f detik",p.optDouble("currentTime",0)):"");taskCounts.setText(p!=null&&p.has("frames")?p.optInt("frames")+" frame · "+p.optInt("audioChunks")+" segmen audio":"");}else{try{JSONObject last=new JSONObject(app.secure.get("lastTask","{}"));taskTitle.setText(last.has("status")?last.optString("status"):"Belum ada aktivitas");taskDetail.setText(last.optBoolean("verified")?"Hasil task terverifikasi.":"Hasil terverifikasi akan muncul setelah ada bukti yang sesuai.");taskTime.setText("");taskCounts.setText("");}catch(Exception ignored){}}}
  private void settings(){content.addView(text("Make it yours.",29,ink,true));space(content,18);LinearLayout c=card();c.addView(text("Suara browser",18,ink,true));c.addView(text("Aktifkan sesi audio untuk mengamati suara dari Hey. Android akan meminta izin sesi; aplikasi lain tidak menjadi sumber audio.",14,muted,false));c.addView(button("Aktifkan audio",this::requestAudio,true));content.addView(c);
    LinearLayout device=card();device.addView(text("Kendali perangkat",18,ink,true));device.addView(button("Pengaturan Android",()->startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName()))),false));device.addView(button("Jeda Hey",()->{startService(new Intent(this,HeyService.class).setAction("STOP"));},false));content.addView(device);content.addView(text("Hey by Ars · 0.1.0\nBrowser, audio, koneksi, dan wake diverifikasi secara terpisah.",12,muted,false));
  }
  private void startBrowser(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},20);startForegroundService(new Intent(this,HeyService.class));}
  private void requestAudio(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},30);return;}startBrowser();startActivityForResult(getSystemService(MediaProjectionManager.class).createScreenCaptureIntent(),31);}
  @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] results){super.onRequestPermissionsResult(request,permissions,results);if(request==30&&results.length>0&&results[0]==PackageManager.PERMISSION_GRANTED)requestAudio();}
  @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==31&&result==RESULT_OK&&data!=null)startForegroundService(new Intent(this,HeyService.class).putExtra("projectionData",data).putExtra("projectionResult",result));if(request==40&&HeyService.current!=null&&HeyService.current.browser!=null)HeyService.current.browser.chooseFile(result==RESULT_OK&&data!=null?data.getData():null);}
  private void pairIntent(Intent intent){Uri uri=intent.getData();if(uri==null||!"hey".equals(uri.getScheme())||!"pair".equals(uri.getHost()))return;intent.setData(null);String gateway=uri.getQueryParameter("gateway"),code=uri.getQueryParameter("code");if(!app.secure.get("deviceToken","").isEmpty()){Toast.makeText(this,"Ponsel ini sudah dipasangkan",Toast.LENGTH_SHORT).show();return;}
    app.state.connection("REGISTERING","");network.execute(()->{try{Transport.gateway(gateway);app.secure.put("gateway",gateway);Transport t=new Transport(app.secure);JSONObject result=t.send("/api/enroll",new JSONObject().put("code",code),false);app.secure.put("deviceId",result.getString("deviceId"));app.secure.put("deviceToken",result.getString("deviceToken"));app.state.connection("PAIRED","");JSONObject config=t.send("/api/config",null,false);if(!config.isNull("firebase")){app.secure.put("firebase",config.getJSONObject("firebase").toString());main.post(()->app.initPush());}main.post(()->{startBrowser();render();});}catch(Exception e){app.state.connection("UNREGISTERED","PAIRING_FAILED");main.post(()->Toast.makeText(this,"Pairing belum berhasil. Minta tautan baru dari Hey.",Toast.LENGTH_LONG).show());}});
  }
  @Override public void changed(){main.post(this::update);}
  private void update(){JSONObject s=app.state.snapshot();if(connection!=null){String status=s.optString("connection");connection.setText(switch(status){case "ONLINE"->"Terhubung";case "PAIRED"->"Ponsel sudah dikenali";case "REGISTERING"->"Menyambungkan…";case "OFFLINE"->"Menghubungkan kembali…";case "UNKNOWN"->"Memeriksa koneksi…";default->"Satu koneksi, sekali saja";});detail.setText(status.equals("ONLINE")?(s.optString("browser").equals("READY")?"Browser siap. Kamu tetap bebas menggunakan ponsel.":"Koneksi tersambung. Browser sedang disiapkan."):"Hubungkan ponsel melalui tautan Hey di ChatGPT.");}updateTasks();}
  private final Runnable previewTick=new Runnable(){@Override public void run(){if(page.equals("Browser")&&browserImage!=null){HeyService s=HeyService.current;if(s!=null&&s.browser!=null){Bitmap frame=s.browser.preview();if(frame!=null&&!frame.isRecycled()){Bitmap next=frame.copy(Bitmap.Config.ARGB_8888,false);browserImage.setImageBitmap(next);if(shown!=null)shown.recycle();shown=next;}}}main.postDelayed(this,700);}};
  @Override protected void onResume(){super.onResume();main.post(previewTick);update();}
  @Override protected void onPause(){main.removeCallbacks(previewTick);super.onPause();}
  @Override protected void onDestroy(){app.state.unlisten(this);main.removeCallbacksAndMessages(null);network.shutdownNow();if(shown!=null)shown.recycle();super.onDestroy();}
}
